/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using SimScale.Sdk.Client;
using SimScale.Sdk.Model;

namespace SimScale.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGeometryImportsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get information about the geometry import
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportId">The geometry import ID</param>
        /// <returns>GeometryImportResponse</returns>
        GeometryImportResponse GetGeometryImport (string projectId = default(string), Guid? geometryImportId = default(Guid?));

        /// <summary>
        /// Get information about the geometry import
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportId">The geometry import ID</param>
        /// <returns>ApiResponse of GeometryImportResponse</returns>
        ApiResponse<GeometryImportResponse> GetGeometryImportWithHttpInfo (string projectId = default(string), Guid? geometryImportId = default(Guid?));
        /// <summary>
        /// Get the geometry import event log
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportId">The geometry import ID</param>
        /// <returns>EventLogResponse</returns>
        EventLogResponse GetGeometryImportEventLog (string projectId = default(string), Guid? geometryImportId = default(Guid?));

        /// <summary>
        /// Get the geometry import event log
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportId">The geometry import ID</param>
        /// <returns>ApiResponse of EventLogResponse</returns>
        ApiResponse<EventLogResponse> GetGeometryImportEventLogWithHttpInfo (string projectId = default(string), Guid? geometryImportId = default(Guid?));
        /// <summary>
        /// Import a new geometry
        /// </summary>
        /// <remarks>
        /// Geometry import requires the following steps: 1. Request a temporary storage location via &#x60;POST /storage&#x60;. 2. Upload your CAD file using the HTTP &#x60;PUT&#x60; method to the &#x60;url&#x60; provided in the temporary storage location response object. 3. Start the import via &#x60;POST /projects/{projectId}/geometryimports&#x60; and include the &#x60;storageId&#x60; provided in the temporary storage location response object. 4. Check for the import status via &#x60;GET /projects/{projectId}/geometryimports/{geometryImportId}&#x60;. 
        /// </remarks>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportRequest">Geometry import specification.</param>
        /// <returns>GeometryImportResponse</returns>
        GeometryImportResponse ImportGeometry (string projectId = default(string), GeometryImportRequest geometryImportRequest = default(GeometryImportRequest));

        /// <summary>
        /// Import a new geometry
        /// </summary>
        /// <remarks>
        /// Geometry import requires the following steps: 1. Request a temporary storage location via &#x60;POST /storage&#x60;. 2. Upload your CAD file using the HTTP &#x60;PUT&#x60; method to the &#x60;url&#x60; provided in the temporary storage location response object. 3. Start the import via &#x60;POST /projects/{projectId}/geometryimports&#x60; and include the &#x60;storageId&#x60; provided in the temporary storage location response object. 4. Check for the import status via &#x60;GET /projects/{projectId}/geometryimports/{geometryImportId}&#x60;. 
        /// </remarks>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportRequest">Geometry import specification.</param>
        /// <returns>ApiResponse of GeometryImportResponse</returns>
        ApiResponse<GeometryImportResponse> ImportGeometryWithHttpInfo (string projectId = default(string), GeometryImportRequest geometryImportRequest = default(GeometryImportRequest));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGeometryImportsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get information about the geometry import
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportId">The geometry import ID</param>
        /// <returns>Task of GeometryImportResponse</returns>
        System.Threading.Tasks.Task<GeometryImportResponse> GetGeometryImportAsync (string projectId = default(string), Guid? geometryImportId = default(Guid?));

        /// <summary>
        /// Get information about the geometry import
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportId">The geometry import ID</param>
        /// <returns>Task of ApiResponse (GeometryImportResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GeometryImportResponse>> GetGeometryImportAsyncWithHttpInfo (string projectId = default(string), Guid? geometryImportId = default(Guid?));
        /// <summary>
        /// Get the geometry import event log
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportId">The geometry import ID</param>
        /// <returns>Task of EventLogResponse</returns>
        System.Threading.Tasks.Task<EventLogResponse> GetGeometryImportEventLogAsync (string projectId = default(string), Guid? geometryImportId = default(Guid?));

        /// <summary>
        /// Get the geometry import event log
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportId">The geometry import ID</param>
        /// <returns>Task of ApiResponse (EventLogResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<EventLogResponse>> GetGeometryImportEventLogAsyncWithHttpInfo (string projectId = default(string), Guid? geometryImportId = default(Guid?));
        /// <summary>
        /// Import a new geometry
        /// </summary>
        /// <remarks>
        /// Geometry import requires the following steps: 1. Request a temporary storage location via &#x60;POST /storage&#x60;. 2. Upload your CAD file using the HTTP &#x60;PUT&#x60; method to the &#x60;url&#x60; provided in the temporary storage location response object. 3. Start the import via &#x60;POST /projects/{projectId}/geometryimports&#x60; and include the &#x60;storageId&#x60; provided in the temporary storage location response object. 4. Check for the import status via &#x60;GET /projects/{projectId}/geometryimports/{geometryImportId}&#x60;. 
        /// </remarks>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportRequest">Geometry import specification.</param>
        /// <returns>Task of GeometryImportResponse</returns>
        System.Threading.Tasks.Task<GeometryImportResponse> ImportGeometryAsync (string projectId = default(string), GeometryImportRequest geometryImportRequest = default(GeometryImportRequest));

        /// <summary>
        /// Import a new geometry
        /// </summary>
        /// <remarks>
        /// Geometry import requires the following steps: 1. Request a temporary storage location via &#x60;POST /storage&#x60;. 2. Upload your CAD file using the HTTP &#x60;PUT&#x60; method to the &#x60;url&#x60; provided in the temporary storage location response object. 3. Start the import via &#x60;POST /projects/{projectId}/geometryimports&#x60; and include the &#x60;storageId&#x60; provided in the temporary storage location response object. 4. Check for the import status via &#x60;GET /projects/{projectId}/geometryimports/{geometryImportId}&#x60;. 
        /// </remarks>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportRequest">Geometry import specification.</param>
        /// <returns>Task of ApiResponse (GeometryImportResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GeometryImportResponse>> ImportGeometryAsyncWithHttpInfo (string projectId = default(string), GeometryImportRequest geometryImportRequest = default(GeometryImportRequest));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGeometryImportsApi : IGeometryImportsApiSync, IGeometryImportsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class GeometryImportsApi : IGeometryImportsApi
    {
        private SimScale.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="GeometryImportsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public GeometryImportsApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GeometryImportsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public GeometryImportsApi(String basePath)
        {
            this.Configuration = SimScale.Sdk.Client.Configuration.MergeConfigurations(
                SimScale.Sdk.Client.GlobalConfiguration.Instance,
                new SimScale.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.Client = new SimScale.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new SimScale.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = SimScale.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GeometryImportsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public GeometryImportsApi(SimScale.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = SimScale.Sdk.Client.Configuration.MergeConfigurations(
                SimScale.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new SimScale.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new SimScale.Sdk.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = SimScale.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GeometryImportsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public GeometryImportsApi(SimScale.Sdk.Client.ISynchronousClient client,SimScale.Sdk.Client.IAsynchronousClient asyncClient, SimScale.Sdk.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = SimScale.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public SimScale.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public SimScale.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public SimScale.Sdk.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public SimScale.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get information about the geometry import 
        /// </summary>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportId">The geometry import ID</param>
        /// <returns>GeometryImportResponse</returns>
        public GeometryImportResponse GetGeometryImport (string projectId = default(string), Guid? geometryImportId = default(Guid?))
        {
             SimScale.Sdk.Client.ApiResponse<GeometryImportResponse> localVarResponse = GetGeometryImportWithHttpInfo(projectId, geometryImportId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get information about the geometry import 
        /// </summary>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportId">The geometry import ID</param>
        /// <returns>ApiResponse of GeometryImportResponse</returns>
        public SimScale.Sdk.Client.ApiResponse< GeometryImportResponse > GetGeometryImportWithHttpInfo (string projectId = default(string), Guid? geometryImportId = default(Guid?))
        {
            // verify the required parameter 'projectId' is set
            if (projectId == null)
                throw new SimScale.Sdk.Client.ApiException(400, "Missing required parameter 'projectId' when calling GeometryImportsApi->GetGeometryImport");

            // verify the required parameter 'geometryImportId' is set
            if (geometryImportId == null)
                throw new SimScale.Sdk.Client.ApiException(400, "Missing required parameter 'geometryImportId' when calling GeometryImportsApi->GetGeometryImport");

            SimScale.Sdk.Client.RequestOptions localVarRequestOptions = new SimScale.Sdk.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = SimScale.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SimScale.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("projectId", SimScale.Sdk.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.PathParameters.Add("geometryImportId", SimScale.Sdk.Client.ClientUtils.ParameterToString(geometryImportId)); // path parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-KEY")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-KEY", this.Configuration.GetApiKeyWithPrefix("X-API-KEY"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< GeometryImportResponse >("/projects/{projectId}/geometryimports/{geometryImportId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetGeometryImport", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get information about the geometry import 
        /// </summary>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportId">The geometry import ID</param>
        /// <returns>Task of GeometryImportResponse</returns>
        public async System.Threading.Tasks.Task<GeometryImportResponse> GetGeometryImportAsync (string projectId = default(string), Guid? geometryImportId = default(Guid?))
        {
             SimScale.Sdk.Client.ApiResponse<GeometryImportResponse> localVarResponse = await GetGeometryImportAsyncWithHttpInfo(projectId, geometryImportId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get information about the geometry import 
        /// </summary>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportId">The geometry import ID</param>
        /// <returns>Task of ApiResponse (GeometryImportResponse)</returns>
        public async System.Threading.Tasks.Task<SimScale.Sdk.Client.ApiResponse<GeometryImportResponse>> GetGeometryImportAsyncWithHttpInfo (string projectId = default(string), Guid? geometryImportId = default(Guid?))
        {
            // verify the required parameter 'projectId' is set
            if (projectId == null)
                throw new SimScale.Sdk.Client.ApiException(400, "Missing required parameter 'projectId' when calling GeometryImportsApi->GetGeometryImport");

            // verify the required parameter 'geometryImportId' is set
            if (geometryImportId == null)
                throw new SimScale.Sdk.Client.ApiException(400, "Missing required parameter 'geometryImportId' when calling GeometryImportsApi->GetGeometryImport");


            SimScale.Sdk.Client.RequestOptions localVarRequestOptions = new SimScale.Sdk.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.PathParameters.Add("projectId", SimScale.Sdk.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.PathParameters.Add("geometryImportId", SimScale.Sdk.Client.ClientUtils.ParameterToString(geometryImportId)); // path parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-KEY")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-KEY", this.Configuration.GetApiKeyWithPrefix("X-API-KEY"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GeometryImportResponse>("/projects/{projectId}/geometryimports/{geometryImportId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetGeometryImport", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get the geometry import event log 
        /// </summary>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportId">The geometry import ID</param>
        /// <returns>EventLogResponse</returns>
        public EventLogResponse GetGeometryImportEventLog (string projectId = default(string), Guid? geometryImportId = default(Guid?))
        {
             SimScale.Sdk.Client.ApiResponse<EventLogResponse> localVarResponse = GetGeometryImportEventLogWithHttpInfo(projectId, geometryImportId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the geometry import event log 
        /// </summary>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportId">The geometry import ID</param>
        /// <returns>ApiResponse of EventLogResponse</returns>
        public SimScale.Sdk.Client.ApiResponse< EventLogResponse > GetGeometryImportEventLogWithHttpInfo (string projectId = default(string), Guid? geometryImportId = default(Guid?))
        {
            // verify the required parameter 'projectId' is set
            if (projectId == null)
                throw new SimScale.Sdk.Client.ApiException(400, "Missing required parameter 'projectId' when calling GeometryImportsApi->GetGeometryImportEventLog");

            // verify the required parameter 'geometryImportId' is set
            if (geometryImportId == null)
                throw new SimScale.Sdk.Client.ApiException(400, "Missing required parameter 'geometryImportId' when calling GeometryImportsApi->GetGeometryImportEventLog");

            SimScale.Sdk.Client.RequestOptions localVarRequestOptions = new SimScale.Sdk.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = SimScale.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SimScale.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("projectId", SimScale.Sdk.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.PathParameters.Add("geometryImportId", SimScale.Sdk.Client.ClientUtils.ParameterToString(geometryImportId)); // path parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-KEY")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-KEY", this.Configuration.GetApiKeyWithPrefix("X-API-KEY"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< EventLogResponse >("/projects/{projectId}/geometryimports/{geometryImportId}/eventlog", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetGeometryImportEventLog", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get the geometry import event log 
        /// </summary>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportId">The geometry import ID</param>
        /// <returns>Task of EventLogResponse</returns>
        public async System.Threading.Tasks.Task<EventLogResponse> GetGeometryImportEventLogAsync (string projectId = default(string), Guid? geometryImportId = default(Guid?))
        {
             SimScale.Sdk.Client.ApiResponse<EventLogResponse> localVarResponse = await GetGeometryImportEventLogAsyncWithHttpInfo(projectId, geometryImportId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the geometry import event log 
        /// </summary>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportId">The geometry import ID</param>
        /// <returns>Task of ApiResponse (EventLogResponse)</returns>
        public async System.Threading.Tasks.Task<SimScale.Sdk.Client.ApiResponse<EventLogResponse>> GetGeometryImportEventLogAsyncWithHttpInfo (string projectId = default(string), Guid? geometryImportId = default(Guid?))
        {
            // verify the required parameter 'projectId' is set
            if (projectId == null)
                throw new SimScale.Sdk.Client.ApiException(400, "Missing required parameter 'projectId' when calling GeometryImportsApi->GetGeometryImportEventLog");

            // verify the required parameter 'geometryImportId' is set
            if (geometryImportId == null)
                throw new SimScale.Sdk.Client.ApiException(400, "Missing required parameter 'geometryImportId' when calling GeometryImportsApi->GetGeometryImportEventLog");


            SimScale.Sdk.Client.RequestOptions localVarRequestOptions = new SimScale.Sdk.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.PathParameters.Add("projectId", SimScale.Sdk.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.PathParameters.Add("geometryImportId", SimScale.Sdk.Client.ClientUtils.ParameterToString(geometryImportId)); // path parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-KEY")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-KEY", this.Configuration.GetApiKeyWithPrefix("X-API-KEY"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<EventLogResponse>("/projects/{projectId}/geometryimports/{geometryImportId}/eventlog", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetGeometryImportEventLog", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Import a new geometry Geometry import requires the following steps: 1. Request a temporary storage location via &#x60;POST /storage&#x60;. 2. Upload your CAD file using the HTTP &#x60;PUT&#x60; method to the &#x60;url&#x60; provided in the temporary storage location response object. 3. Start the import via &#x60;POST /projects/{projectId}/geometryimports&#x60; and include the &#x60;storageId&#x60; provided in the temporary storage location response object. 4. Check for the import status via &#x60;GET /projects/{projectId}/geometryimports/{geometryImportId}&#x60;. 
        /// </summary>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportRequest">Geometry import specification.</param>
        /// <returns>GeometryImportResponse</returns>
        public GeometryImportResponse ImportGeometry (string projectId = default(string), GeometryImportRequest geometryImportRequest = default(GeometryImportRequest))
        {
             SimScale.Sdk.Client.ApiResponse<GeometryImportResponse> localVarResponse = ImportGeometryWithHttpInfo(projectId, geometryImportRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Import a new geometry Geometry import requires the following steps: 1. Request a temporary storage location via &#x60;POST /storage&#x60;. 2. Upload your CAD file using the HTTP &#x60;PUT&#x60; method to the &#x60;url&#x60; provided in the temporary storage location response object. 3. Start the import via &#x60;POST /projects/{projectId}/geometryimports&#x60; and include the &#x60;storageId&#x60; provided in the temporary storage location response object. 4. Check for the import status via &#x60;GET /projects/{projectId}/geometryimports/{geometryImportId}&#x60;. 
        /// </summary>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportRequest">Geometry import specification.</param>
        /// <returns>ApiResponse of GeometryImportResponse</returns>
        public SimScale.Sdk.Client.ApiResponse< GeometryImportResponse > ImportGeometryWithHttpInfo (string projectId = default(string), GeometryImportRequest geometryImportRequest = default(GeometryImportRequest))
        {
            // verify the required parameter 'projectId' is set
            if (projectId == null)
                throw new SimScale.Sdk.Client.ApiException(400, "Missing required parameter 'projectId' when calling GeometryImportsApi->ImportGeometry");

            // verify the required parameter 'geometryImportRequest' is set
            if (geometryImportRequest == null)
                throw new SimScale.Sdk.Client.ApiException(400, "Missing required parameter 'geometryImportRequest' when calling GeometryImportsApi->ImportGeometry");

            SimScale.Sdk.Client.RequestOptions localVarRequestOptions = new SimScale.Sdk.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = SimScale.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SimScale.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("projectId", SimScale.Sdk.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.Data = geometryImportRequest;

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-KEY")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-KEY", this.Configuration.GetApiKeyWithPrefix("X-API-KEY"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post< GeometryImportResponse >("/projects/{projectId}/geometryimports", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ImportGeometry", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Import a new geometry Geometry import requires the following steps: 1. Request a temporary storage location via &#x60;POST /storage&#x60;. 2. Upload your CAD file using the HTTP &#x60;PUT&#x60; method to the &#x60;url&#x60; provided in the temporary storage location response object. 3. Start the import via &#x60;POST /projects/{projectId}/geometryimports&#x60; and include the &#x60;storageId&#x60; provided in the temporary storage location response object. 4. Check for the import status via &#x60;GET /projects/{projectId}/geometryimports/{geometryImportId}&#x60;. 
        /// </summary>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportRequest">Geometry import specification.</param>
        /// <returns>Task of GeometryImportResponse</returns>
        public async System.Threading.Tasks.Task<GeometryImportResponse> ImportGeometryAsync (string projectId = default(string), GeometryImportRequest geometryImportRequest = default(GeometryImportRequest))
        {
             SimScale.Sdk.Client.ApiResponse<GeometryImportResponse> localVarResponse = await ImportGeometryAsyncWithHttpInfo(projectId, geometryImportRequest);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Import a new geometry Geometry import requires the following steps: 1. Request a temporary storage location via &#x60;POST /storage&#x60;. 2. Upload your CAD file using the HTTP &#x60;PUT&#x60; method to the &#x60;url&#x60; provided in the temporary storage location response object. 3. Start the import via &#x60;POST /projects/{projectId}/geometryimports&#x60; and include the &#x60;storageId&#x60; provided in the temporary storage location response object. 4. Check for the import status via &#x60;GET /projects/{projectId}/geometryimports/{geometryImportId}&#x60;. 
        /// </summary>
        /// <exception cref="SimScale.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The project ID</param>
        /// <param name="geometryImportRequest">Geometry import specification.</param>
        /// <returns>Task of ApiResponse (GeometryImportResponse)</returns>
        public async System.Threading.Tasks.Task<SimScale.Sdk.Client.ApiResponse<GeometryImportResponse>> ImportGeometryAsyncWithHttpInfo (string projectId = default(string), GeometryImportRequest geometryImportRequest = default(GeometryImportRequest))
        {
            // verify the required parameter 'projectId' is set
            if (projectId == null)
                throw new SimScale.Sdk.Client.ApiException(400, "Missing required parameter 'projectId' when calling GeometryImportsApi->ImportGeometry");

            // verify the required parameter 'geometryImportRequest' is set
            if (geometryImportRequest == null)
                throw new SimScale.Sdk.Client.ApiException(400, "Missing required parameter 'geometryImportRequest' when calling GeometryImportsApi->ImportGeometry");


            SimScale.Sdk.Client.RequestOptions localVarRequestOptions = new SimScale.Sdk.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.PathParameters.Add("projectId", SimScale.Sdk.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.Data = geometryImportRequest;

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-KEY")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-KEY", this.Configuration.GetApiKeyWithPrefix("X-API-KEY"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<GeometryImportResponse>("/projects/{projectId}/geometryimports", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ImportGeometry", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
