/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// AutomaticLayerOn
    /// </summary>
    [DataContract]
    public partial class AutomaticLayerOn : OneOfSimmetrixMeshingFluidAutomaticLayerSettings, IEquatable<AutomaticLayerOn>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AutomaticLayerOn" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AutomaticLayerOn() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AutomaticLayerOn" /> class.
        /// </summary>
        /// <param name="type">Schema name: AutomaticLayerOn (required) (default to &quot;AUTOMATIC_LAYER_ON&quot;).</param>
        /// <param name="layerType">layerType.</param>
        public AutomaticLayerOn(string type = "AUTOMATIC_LAYER_ON", OneOfAutomaticLayerOnLayerType layerType = default(OneOfAutomaticLayerOnLayerType))
        {
            // to ensure "type" is required (not null)
            this.Type = type ?? throw new ArgumentNullException("type is a required property for AutomaticLayerOn and cannot be null");
            this.LayerType = layerType;
        }
        
        /// <summary>
        /// Schema name: AutomaticLayerOn
        /// </summary>
        /// <value>Schema name: AutomaticLayerOn</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets LayerType
        /// </summary>
        [DataMember(Name="layerType", EmitDefaultValue=false)]
        public OneOfAutomaticLayerOnLayerType LayerType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AutomaticLayerOn {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  LayerType: ").Append(LayerType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AutomaticLayerOn);
        }

        /// <summary>
        /// Returns true if AutomaticLayerOn instances are equal
        /// </summary>
        /// <param name="input">Instance of AutomaticLayerOn to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AutomaticLayerOn input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.LayerType == input.LayerType ||
                    (this.LayerType != null &&
                    this.LayerType.Equals(input.LayerType))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.LayerType != null)
                    hashCode = hashCode * 59 + this.LayerType.GetHashCode();
                return hashCode;
            }
        }

    }

}
