/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// DirectionalMaterialStructure
    /// </summary>
    [DataContract]
    public partial class DirectionalMaterialStructure : OneOfDarcyMediumPorousMaterialType, OneOfPressureLossFunctionMediumPorousMaterialType, IEquatable<DirectionalMaterialStructure>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DirectionalMaterialStructure" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DirectionalMaterialStructure() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DirectionalMaterialStructure" /> class.
        /// </summary>
        /// <param name="type">Schema name: DirectionalMaterialStructure (required) (default to &quot;DIRECTIONAL&quot;).</param>
        /// <param name="mode">mode.</param>
        /// <param name="direction">direction.</param>
        /// <param name="orientation">orientation.</param>
        public DirectionalMaterialStructure(string type = "DIRECTIONAL", OneOfDirectionalMaterialStructureMode mode = default(OneOfDirectionalMaterialStructureMode), DimensionalVectorDimensionless direction = default(DimensionalVectorDimensionless), OneOfDirectionalMaterialStructureOrientation orientation = default(OneOfDirectionalMaterialStructureOrientation))
        {
            // to ensure "type" is required (not null)
            this.Type = type ?? throw new ArgumentNullException("type is a required property for DirectionalMaterialStructure and cannot be null");
            this.Mode = mode;
            this.Direction = direction;
            this.Orientation = orientation;
        }
        
        /// <summary>
        /// Schema name: DirectionalMaterialStructure
        /// </summary>
        /// <value>Schema name: DirectionalMaterialStructure</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Mode
        /// </summary>
        [DataMember(Name="mode", EmitDefaultValue=false)]
        public OneOfDirectionalMaterialStructureMode Mode { get; set; }

        /// <summary>
        /// Gets or Sets Direction
        /// </summary>
        [DataMember(Name="direction", EmitDefaultValue=false)]
        public DimensionalVectorDimensionless Direction { get; set; }

        /// <summary>
        /// Gets or Sets Orientation
        /// </summary>
        [DataMember(Name="orientation", EmitDefaultValue=false)]
        public OneOfDirectionalMaterialStructureOrientation Orientation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DirectionalMaterialStructure {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("  Direction: ").Append(Direction).Append("\n");
            sb.Append("  Orientation: ").Append(Orientation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DirectionalMaterialStructure);
        }

        /// <summary>
        /// Returns true if DirectionalMaterialStructure instances are equal
        /// </summary>
        /// <param name="input">Instance of DirectionalMaterialStructure to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DirectionalMaterialStructure input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Mode == input.Mode ||
                    (this.Mode != null &&
                    this.Mode.Equals(input.Mode))
                ) && 
                (
                    this.Direction == input.Direction ||
                    (this.Direction != null &&
                    this.Direction.Equals(input.Direction))
                ) && 
                (
                    this.Orientation == input.Orientation ||
                    (this.Orientation != null &&
                    this.Orientation.Equals(input.Orientation))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Mode != null)
                    hashCode = hashCode * 59 + this.Mode.GetHashCode();
                if (this.Direction != null)
                    hashCode = hashCode * 59 + this.Direction.GetHashCode();
                if (this.Orientation != null)
                    hashCode = hashCode * 59 + this.Orientation.GetHashCode();
                return hashCode;
            }
        }

    }

}
