/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// GlobalCartesianMagnetizationDirectionMethod
    /// </summary>
    [DataContract]
    public partial class GlobalCartesianMagnetizationDirectionMethod : OneOfPermanentMagnetMaterialMagnetizationDirectionType, IEquatable<GlobalCartesianMagnetizationDirectionMethod>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GlobalCartesianMagnetizationDirectionMethod" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GlobalCartesianMagnetizationDirectionMethod() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GlobalCartesianMagnetizationDirectionMethod" /> class.
        /// </summary>
        /// <param name="type">Schema name: GlobalCartesianMagnetizationDirectionMethod (required) (default to &quot;GLOBAL_CARTESIAN&quot;).</param>
        /// <param name="magnetizationDirection">magnetizationDirection.</param>
        public GlobalCartesianMagnetizationDirectionMethod(string type = "GLOBAL_CARTESIAN", DimensionalVectorDimensionless magnetizationDirection = default(DimensionalVectorDimensionless))
        {
            // to ensure "type" is required (not null)
            this.Type = type ?? throw new ArgumentNullException("type is a required property for GlobalCartesianMagnetizationDirectionMethod and cannot be null");
            this.MagnetizationDirection = magnetizationDirection;
        }
        
        /// <summary>
        /// Schema name: GlobalCartesianMagnetizationDirectionMethod
        /// </summary>
        /// <value>Schema name: GlobalCartesianMagnetizationDirectionMethod</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets MagnetizationDirection
        /// </summary>
        [DataMember(Name="magnetizationDirection", EmitDefaultValue=false)]
        public DimensionalVectorDimensionless MagnetizationDirection { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GlobalCartesianMagnetizationDirectionMethod {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  MagnetizationDirection: ").Append(MagnetizationDirection).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GlobalCartesianMagnetizationDirectionMethod);
        }

        /// <summary>
        /// Returns true if GlobalCartesianMagnetizationDirectionMethod instances are equal
        /// </summary>
        /// <param name="input">Instance of GlobalCartesianMagnetizationDirectionMethod to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GlobalCartesianMagnetizationDirectionMethod input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.MagnetizationDirection == input.MagnetizationDirection ||
                    (this.MagnetizationDirection != null &&
                    this.MagnetizationDirection.Equals(input.MagnetizationDirection))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.MagnetizationDirection != null)
                    hashCode = hashCode * 59 + this.MagnetizationDirection.GetHashCode();
                return hashCode;
            }
        }

    }

}
