/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// IsotropicThermalConductivityMethod
    /// </summary>
    [DataContract]
    public partial class IsotropicThermalConductivityMethod : IEquatable<IsotropicThermalConductivityMethod>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IsotropicThermalConductivityMethod" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected IsotropicThermalConductivityMethod() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="IsotropicThermalConductivityMethod" /> class.
        /// </summary>
        /// <param name="type">Schema name: IsotropicThermalConductivityMethod (required) (default to &quot;ISOTROPIC_THERMAL_CONDUCTIVITY&quot;).</param>
        /// <param name="thermalConductivity">thermalConductivity.</param>
        public IsotropicThermalConductivityMethod(string type = "ISOTROPIC_THERMAL_CONDUCTIVITY", DimensionalFunctionThermalConductivity thermalConductivity = default(DimensionalFunctionThermalConductivity))
        {
            // to ensure "type" is required (not null)
            this.Type = type ?? throw new ArgumentNullException("type is a required property for IsotropicThermalConductivityMethod and cannot be null");
            this.ThermalConductivity = thermalConductivity;
        }
        
        /// <summary>
        /// Schema name: IsotropicThermalConductivityMethod
        /// </summary>
        /// <value>Schema name: IsotropicThermalConductivityMethod</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets ThermalConductivity
        /// </summary>
        [DataMember(Name="thermalConductivity", EmitDefaultValue=false)]
        public DimensionalFunctionThermalConductivity ThermalConductivity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IsotropicThermalConductivityMethod {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  ThermalConductivity: ").Append(ThermalConductivity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as IsotropicThermalConductivityMethod);
        }

        /// <summary>
        /// Returns true if IsotropicThermalConductivityMethod instances are equal
        /// </summary>
        /// <param name="input">Instance of IsotropicThermalConductivityMethod to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IsotropicThermalConductivityMethod input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.ThermalConductivity == input.ThermalConductivity ||
                    (this.ThermalConductivity != null &&
                    this.ThermalConductivity.Equals(input.ThermalConductivity))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.ThermalConductivity != null)
                    hashCode = hashCode * 59 + this.ThermalConductivity.GetHashCode();
                return hashCode;
            }
        }

    }

}
