/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// &lt;p&gt;Define the Creep formulation. Two fundamental Creep law types are available: &lt;ul&gt;&lt;li&gt;&lt;b&gt;Power Law&lt;/b&gt;&lt;/li&gt;&lt;b&gt;&amp;epsilon;&amp;#775 &#x3D; m*A*&amp;sigma;&lt;sup&gt;n&lt;/sup&gt;*t&lt;sup&gt;m-1&lt;/sup&gt;&lt;/b&gt;&lt;li&gt;&lt;b&gt;Hyperbolic Sine Law&lt;/b&gt; &lt;/li&gt;&lt;b&gt;&amp;epsilon;&amp;#775;&#x3D; &amp;epsilon;&lt;sub&gt;0&lt;/sub&gt;* sinh(&amp;sigma;/(&amp;sigma;&lt;sub&gt;0&lt;/sub&gt;))&lt;sup&gt;n&lt;/sup&gt;&lt;/b&gt;.&lt;/ul&gt; For the Power Law different formulations, like the &lt;b&gt;Norton&lt;/b&gt;, &lt;b&gt;Strain Hardening&lt;/b&gt; or &lt;b&gt;Time Hardening&lt;/b&gt; are available. For the Hyperbolic Sine Law, the &lt;b&gt;Garofalo&lt;b&gt; formulation is available.&lt;/p&gt;
    /// </summary>
    [DataContract]
    public partial class NoCreepFormulation : OneOfLinearElasticMaterialBehaviorCreepFormulation, OneOfPlasticMaterialBehaviorCreepFormulation, IEquatable<NoCreepFormulation>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NoCreepFormulation" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NoCreepFormulation() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NoCreepFormulation" /> class.
        /// </summary>
        /// <param name="type">&lt;p&gt;Define the Creep formulation. Two fundamental Creep law types are available: &lt;ul&gt;&lt;li&gt;&lt;b&gt;Power Law&lt;/b&gt;&lt;/li&gt;&lt;b&gt;&amp;epsilon;&amp;#775 &#x3D; m*A*&amp;sigma;&lt;sup&gt;n&lt;/sup&gt;*t&lt;sup&gt;m-1&lt;/sup&gt;&lt;/b&gt;&lt;li&gt;&lt;b&gt;Hyperbolic Sine Law&lt;/b&gt; &lt;/li&gt;&lt;b&gt;&amp;epsilon;&amp;#775;&#x3D; &amp;epsilon;&lt;sub&gt;0&lt;/sub&gt;* sinh(&amp;sigma;/(&amp;sigma;&lt;sub&gt;0&lt;/sub&gt;))&lt;sup&gt;n&lt;/sup&gt;&lt;/b&gt;.&lt;/ul&gt; For the Power Law different formulations, like the &lt;b&gt;Norton&lt;/b&gt;, &lt;b&gt;Strain Hardening&lt;/b&gt; or &lt;b&gt;Time Hardening&lt;/b&gt; are available. For the Hyperbolic Sine Law, the &lt;b&gt;Garofalo&lt;b&gt; formulation is available.&lt;/p&gt;  Schema name: NoCreepFormulation (required) (default to &quot;NO_CREEP&quot;).</param>
        public NoCreepFormulation(string type = "NO_CREEP")
        {
            // to ensure "type" is required (not null)
            this.Type = type ?? throw new ArgumentNullException("type is a required property for NoCreepFormulation and cannot be null");
        }
        
        /// <summary>
        /// &lt;p&gt;Define the Creep formulation. Two fundamental Creep law types are available: &lt;ul&gt;&lt;li&gt;&lt;b&gt;Power Law&lt;/b&gt;&lt;/li&gt;&lt;b&gt;&amp;epsilon;&amp;#775 &#x3D; m*A*&amp;sigma;&lt;sup&gt;n&lt;/sup&gt;*t&lt;sup&gt;m-1&lt;/sup&gt;&lt;/b&gt;&lt;li&gt;&lt;b&gt;Hyperbolic Sine Law&lt;/b&gt; &lt;/li&gt;&lt;b&gt;&amp;epsilon;&amp;#775;&#x3D; &amp;epsilon;&lt;sub&gt;0&lt;/sub&gt;* sinh(&amp;sigma;/(&amp;sigma;&lt;sub&gt;0&lt;/sub&gt;))&lt;sup&gt;n&lt;/sup&gt;&lt;/b&gt;.&lt;/ul&gt; For the Power Law different formulations, like the &lt;b&gt;Norton&lt;/b&gt;, &lt;b&gt;Strain Hardening&lt;/b&gt; or &lt;b&gt;Time Hardening&lt;/b&gt; are available. For the Hyperbolic Sine Law, the &lt;b&gt;Garofalo&lt;b&gt; formulation is available.&lt;/p&gt;  Schema name: NoCreepFormulation
        /// </summary>
        /// <value>&lt;p&gt;Define the Creep formulation. Two fundamental Creep law types are available: &lt;ul&gt;&lt;li&gt;&lt;b&gt;Power Law&lt;/b&gt;&lt;/li&gt;&lt;b&gt;&amp;epsilon;&amp;#775 &#x3D; m*A*&amp;sigma;&lt;sup&gt;n&lt;/sup&gt;*t&lt;sup&gt;m-1&lt;/sup&gt;&lt;/b&gt;&lt;li&gt;&lt;b&gt;Hyperbolic Sine Law&lt;/b&gt; &lt;/li&gt;&lt;b&gt;&amp;epsilon;&amp;#775;&#x3D; &amp;epsilon;&lt;sub&gt;0&lt;/sub&gt;* sinh(&amp;sigma;/(&amp;sigma;&lt;sub&gt;0&lt;/sub&gt;))&lt;sup&gt;n&lt;/sup&gt;&lt;/b&gt;.&lt;/ul&gt; For the Power Law different formulations, like the &lt;b&gt;Norton&lt;/b&gt;, &lt;b&gt;Strain Hardening&lt;/b&gt; or &lt;b&gt;Time Hardening&lt;/b&gt; are available. For the Hyperbolic Sine Law, the &lt;b&gt;Garofalo&lt;b&gt; formulation is available.&lt;/p&gt;  Schema name: NoCreepFormulation</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NoCreepFormulation {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NoCreepFormulation);
        }

        /// <summary>
        /// Returns true if NoCreepFormulation instances are equal
        /// </summary>
        /// <param name="input">Instance of NoCreepFormulation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NoCreepFormulation input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                return hashCode;
            }
        }

    }

}
