/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// NoSlipWallAerodynamicRoughness
    /// </summary>
    [DataContract]
    public partial class NoSlipWallAerodynamicRoughness : OneOfNoSlipVBCNoSlipWallRoughnessType, IEquatable<NoSlipWallAerodynamicRoughness>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NoSlipWallAerodynamicRoughness" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NoSlipWallAerodynamicRoughness() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NoSlipWallAerodynamicRoughness" /> class.
        /// </summary>
        /// <param name="type">Schema name: NoSlipWallAerodynamicRoughness (required) (default to &quot;NO_SLIP_WALL_AERODYNAMIC_ROUGHNESS&quot;).</param>
        /// <param name="surfaceRoughness">surfaceRoughness.</param>
        public NoSlipWallAerodynamicRoughness(string type = "NO_SLIP_WALL_AERODYNAMIC_ROUGHNESS", DimensionalLength surfaceRoughness = default(DimensionalLength))
        {
            // to ensure "type" is required (not null)
            this.Type = type ?? throw new ArgumentNullException("type is a required property for NoSlipWallAerodynamicRoughness and cannot be null");
            this.SurfaceRoughness = surfaceRoughness;
        }
        
        /// <summary>
        /// Schema name: NoSlipWallAerodynamicRoughness
        /// </summary>
        /// <value>Schema name: NoSlipWallAerodynamicRoughness</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets SurfaceRoughness
        /// </summary>
        [DataMember(Name="surfaceRoughness", EmitDefaultValue=false)]
        public DimensionalLength SurfaceRoughness { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NoSlipWallAerodynamicRoughness {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  SurfaceRoughness: ").Append(SurfaceRoughness).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NoSlipWallAerodynamicRoughness);
        }

        /// <summary>
        /// Returns true if NoSlipWallAerodynamicRoughness instances are equal
        /// </summary>
        /// <param name="input">Instance of NoSlipWallAerodynamicRoughness to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NoSlipWallAerodynamicRoughness input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.SurfaceRoughness == input.SurfaceRoughness ||
                    (this.SurfaceRoughness != null &&
                    this.SurfaceRoughness.Equals(input.SurfaceRoughness))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.SurfaceRoughness != null)
                    hashCode = hashCode * 59 + this.SurfaceRoughness.GetHashCode();
                return hashCode;
            }
        }

    }

}
