/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using JsonSubTypes;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// &lt;p&gt;Choose how your mesh element sizes should be defined:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;p&gt;If you select the &lt;b&gt;automatic&lt;/b&gt; sizing, you can specify how fine your mesh should be (ranging from &lt;i&gt;1 - very coarse&lt;/i&gt; to &lt;i&gt;5 - very fine&lt;/i&gt;) and all additional parameters will be set automatically according to the chosen fineness and the geometry features.&lt;/ul&gt;&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;p&gt;For full control over the mesh sizing, select the &lt;b&gt;manual&lt;/b&gt; option. Here you can in addition to the &lt;i&gt;minimum edge length&lt;/i&gt; and &lt;i&gt;maximum edge length&lt;/i&gt; define the &lt;i&gt;mesh grading&lt;/i&gt; in a very detailed manner.&lt;/ul&gt;&lt;/p&gt;&lt;p&gt;&lt;img src&#x3D;\&quot;/spec/resources/help/imgs/mesh_fineness_comparison.png\&quot; class&#x3D;\&quot;helpPopupImage\&quot;/&gt; The figure shows meshes for fineness &lt;i&gt;1 - very coarse&lt;/i&gt; (left) and &lt;i&gt;5 - very fine&lt;/i&gt; (right).&lt;/p&gt;
    /// </summary>
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    [JsonSubtypes.KnownSubType(typeof(AutomaticMeshSizingHexDominantSnappy), "AUTOMATIC")]
    [JsonSubtypes.KnownSubType(typeof(ManualMeshSizingHexDominantSnappy), "MANUAL")]
    public interface OneOfHexDominantSnappySizing
    {
        /// <summary>
        /// Gets Type
        /// </summary>
        string Type { get; }
    }
}
