/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using JsonSubTypes;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// Choose the preconditioner for the iterative solver:&lt;ul&gt;&lt;li&gt;&lt;p&gt;&lt;b&gt;incomplete LDLT&lt;/b&gt; performs an incomplete Cholesky decomposition.&lt;/p&gt;&lt;/ul&gt;&lt;ul&gt;&lt;li&gt;&lt;p&gt;&lt;b&gt;MUMPS LDLT&lt;/b&gt; performs a complete Cholesky decomposition in single precision via the MUMPS package.&lt;/p&gt;&lt;/ul&gt;&lt;ul&gt;&lt;li&gt;&lt;p&gt;&lt;b&gt;Jacobi&lt;/b&gt; is a standard diagonal preconditioner.&lt;/p&gt;&lt;/ul&gt;&lt;ul&gt;&lt;li&gt;&lt;p&gt;&lt;b&gt;SOR&lt;/b&gt; uses the method of &lt;i&gt;Successive Over-Relaxation&lt;/i&gt;.&lt;/p&gt;&lt;/ul&gt;
    /// </summary>
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    [JsonSubtypes.KnownSubType(typeof(MUMPSPreconditoner), "MUMPS_LDLT")]
    [JsonSubtypes.KnownSubType(typeof(IncompletePreconditioner), "INCOMPLETE_LDLT")]
    [JsonSubtypes.KnownSubType(typeof(IncompletePreconditionerV33), "INCOMPLETE_LDLT_V33")]
    [JsonSubtypes.KnownSubType(typeof(JacobiPreconditioner), "JACOBI")]
    [JsonSubtypes.KnownSubType(typeof(SorPreconditioner), "SOR")]
    [JsonSubtypes.KnownSubType(typeof(InactivePreconditioner), "INACTIVE")]
    public interface OneOfPETSCSolverPreconditioner
    {
        /// <summary>
        /// Gets Type
        /// </summary>
        string Type { get; }
    }
}
