/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using JsonSubTypes;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// Choose the direction for applying fluid resistance: &lt;p&gt;&lt;ul&gt; &lt;li&gt;&lt;b&gt;Allowed:&lt;/b&gt; Fluid resistance is applied in the chosen direction, while fluid flow is blocked in the other two orthogonal directions.&lt;/li&gt; &lt;li&gt;&lt;b&gt;Blocked:&lt;/b&gt; Fluid flow is blocked in the chosen direction, and fluid resistance is applied in the other two orthogonal directions.&lt;/li&gt; &lt;/ul&gt;&lt;/p&gt;
    /// </summary>
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    [JsonSubtypes.KnownSubType(typeof(AllowedDirection), "ALLOWED_DIRECTION")]
    [JsonSubtypes.KnownSubType(typeof(BlockedDirection), "BLOCKED_DIRECTION")]
    public interface OneOfDirectionalMaterialStructureMode
    {
        /// <summary>
        /// Gets Type
        /// </summary>
        string Type { get; }
    }
}
