/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using JsonSubTypes;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// &lt;p&gt;Define the rotational behavior between the connected entities&lt;br /&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Free rotation&lt;/b&gt; - bodies may freely rotate about the pin axis&lt;/li&gt;&lt;li&gt;&lt;b&gt;Rigid&lt;/b&gt; - rotation of the bodies about the pin axis direction is locked&lt;/li&gt;&lt;li&gt;&lt;b&gt;With torsion spring&lt;/b&gt; - rotation is controlled by a torsion spring stiffness&lt;/li&gt;&lt;/ul&gt;&lt;/p&gt;
    /// </summary>
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    [JsonSubtypes.KnownSubType(typeof(FreeAxialRotation), "FREE")]
    [JsonSubtypes.KnownSubType(typeof(RigidAxialRotation), "RIGID")]
    [JsonSubtypes.KnownSubType(typeof(TorsionalAxialRotation), "TORSIONAL")]
    public interface OneOfPinKinematicBehaviorRotation
    {
        /// <summary>
        /// Gets Type
        /// </summary>
        string Type { get; }
    }
}
