/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using JsonSubTypes;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// &lt;p&gt;Define the translation behavior between the connected entities along the virtual pin axis&lt;br /&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Free sliding&lt;/b&gt; - bodies may freely translate along the pin axis&lt;/li&gt;&lt;li&gt;&lt;b&gt;Rigid&lt;/b&gt; - translation of the bodies in the pin axis direction is locked&lt;/li&gt;&lt;li&gt;&lt;b&gt;With axial spring&lt;/b&gt; - translation is controlled by an axial spring stiffness, allowing the deformation of the virtual pin itself to affect global deformations&lt;/li&gt;&lt;/ul&gt;&lt;/p&gt;
    /// </summary>
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    [JsonSubtypes.KnownSubType(typeof(FreeAxialTranslation), "FREE")]
    [JsonSubtypes.KnownSubType(typeof(RigidAxialTranslation), "RIGID")]
    [JsonSubtypes.KnownSubType(typeof(FlexibleAxialTranslation), "FLEXIBLE")]
    public interface OneOfPinKinematicBehaviorAxialTranslation
    {
        /// <summary>
        /// Gets Type
        /// </summary>
        string Type { get; }
    }
}
