/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// PacefishAutomesh
    /// </summary>
    [DataContract]
    public partial class PacefishAutomesh : OneOfIncompressiblePacefishMeshSettingsNew, IEquatable<PacefishAutomesh>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PacefishAutomesh" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PacefishAutomesh() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PacefishAutomesh" /> class.
        /// </summary>
        /// <param name="type">Schema name: PacefishAutomesh (required) (default to &quot;PACEFISH_AUTOMESH&quot;).</param>
        /// <param name="newFineness">newFineness.</param>
        /// <param name="referenceLengthComputation">referenceLengthComputation.</param>
        /// <param name="primaryTopology">primaryTopology.</param>
        /// <param name="refinements">refinements.</param>
        public PacefishAutomesh(string type = "PACEFISH_AUTOMESH", OneOfPacefishAutomeshNewFineness newFineness = default(OneOfPacefishAutomeshNewFineness), OneOfPacefishAutomeshReferenceLengthComputation referenceLengthComputation = default(OneOfPacefishAutomeshReferenceLengthComputation), OneOfPacefishAutomeshPrimaryTopology primaryTopology = default(OneOfPacefishAutomeshPrimaryTopology), List<OneOfPacefishAutomeshRefinements> refinements = default(List<OneOfPacefishAutomeshRefinements>))
        {
            // to ensure "type" is required (not null)
            this.Type = type ?? throw new ArgumentNullException("type is a required property for PacefishAutomesh and cannot be null");
            this.NewFineness = newFineness;
            this.ReferenceLengthComputation = referenceLengthComputation;
            this.PrimaryTopology = primaryTopology;
            this.Refinements = refinements;
        }
        
        /// <summary>
        /// Schema name: PacefishAutomesh
        /// </summary>
        /// <value>Schema name: PacefishAutomesh</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets NewFineness
        /// </summary>
        [DataMember(Name="newFineness", EmitDefaultValue=false)]
        public OneOfPacefishAutomeshNewFineness NewFineness { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceLengthComputation
        /// </summary>
        [DataMember(Name="referenceLengthComputation", EmitDefaultValue=false)]
        public OneOfPacefishAutomeshReferenceLengthComputation ReferenceLengthComputation { get; set; }

        /// <summary>
        /// Gets or Sets PrimaryTopology
        /// </summary>
        [DataMember(Name="primaryTopology", EmitDefaultValue=false)]
        public OneOfPacefishAutomeshPrimaryTopology PrimaryTopology { get; set; }

        /// <summary>
        /// Gets or Sets Refinements
        /// </summary>
        [DataMember(Name="refinements", EmitDefaultValue=false)]
        public List<OneOfPacefishAutomeshRefinements> Refinements { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PacefishAutomesh {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  NewFineness: ").Append(NewFineness).Append("\n");
            sb.Append("  ReferenceLengthComputation: ").Append(ReferenceLengthComputation).Append("\n");
            sb.Append("  PrimaryTopology: ").Append(PrimaryTopology).Append("\n");
            sb.Append("  Refinements: ").Append(Refinements).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PacefishAutomesh);
        }

        /// <summary>
        /// Returns true if PacefishAutomesh instances are equal
        /// </summary>
        /// <param name="input">Instance of PacefishAutomesh to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PacefishAutomesh input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.NewFineness == input.NewFineness ||
                    (this.NewFineness != null &&
                    this.NewFineness.Equals(input.NewFineness))
                ) && 
                (
                    this.ReferenceLengthComputation == input.ReferenceLengthComputation ||
                    (this.ReferenceLengthComputation != null &&
                    this.ReferenceLengthComputation.Equals(input.ReferenceLengthComputation))
                ) && 
                (
                    this.PrimaryTopology == input.PrimaryTopology ||
                    (this.PrimaryTopology != null &&
                    this.PrimaryTopology.Equals(input.PrimaryTopology))
                ) && 
                (
                    this.Refinements == input.Refinements ||
                    this.Refinements != null &&
                    input.Refinements != null &&
                    this.Refinements.SequenceEqual(input.Refinements)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.NewFineness != null)
                    hashCode = hashCode * 59 + this.NewFineness.GetHashCode();
                if (this.ReferenceLengthComputation != null)
                    hashCode = hashCode * 59 + this.ReferenceLengthComputation.GetHashCode();
                if (this.PrimaryTopology != null)
                    hashCode = hashCode * 59 + this.PrimaryTopology.GetHashCode();
                if (this.Refinements != null)
                    hashCode = hashCode * 59 + this.Refinements.GetHashCode();
                return hashCode;
            }
        }

    }

}
