/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// ProjectCopyRequest
    /// </summary>
    [DataContract]
    public partial class ProjectCopyRequest : IEquatable<ProjectCopyRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectCopyRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProjectCopyRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectCopyRequest" /> class.
        /// </summary>
        /// <param name="spaceId">If missing, the project will be copied in the Personal Space of the user..</param>
        /// <param name="parentFolderId">If missing, the project is located at the root level of the Space..</param>
        /// <param name="name">The project title should contain the application you want to analyze as well as the simulation method you want to use, e.g. &#39;Heat exchanger - CHT simulation&#39;.  (required).</param>
        /// <param name="description">A meaningful description of the project. (required).</param>
        public ProjectCopyRequest(Guid? spaceId = default(Guid?), Guid? parentFolderId = default(Guid?), string name = default(string), string description = default(string))
        {
            // to ensure "name" is required (not null)
            this.Name = name ?? throw new ArgumentNullException("name is a required property for ProjectCopyRequest and cannot be null");
            // to ensure "description" is required (not null)
            this.Description = description ?? throw new ArgumentNullException("description is a required property for ProjectCopyRequest and cannot be null");
            this.SpaceId = spaceId;
            this.ParentFolderId = parentFolderId;
        }
        
        /// <summary>
        /// If missing, the project will be copied in the Personal Space of the user.
        /// </summary>
        /// <value>If missing, the project will be copied in the Personal Space of the user.</value>
        [DataMember(Name="spaceId", EmitDefaultValue=false)]
        public Guid? SpaceId { get; set; }

        /// <summary>
        /// If missing, the project is located at the root level of the Space.
        /// </summary>
        /// <value>If missing, the project is located at the root level of the Space.</value>
        [DataMember(Name="parentFolderId", EmitDefaultValue=false)]
        public Guid? ParentFolderId { get; set; }

        /// <summary>
        /// The project title should contain the application you want to analyze as well as the simulation method you want to use, e.g. &#39;Heat exchanger - CHT simulation&#39;. 
        /// </summary>
        /// <value>The project title should contain the application you want to analyze as well as the simulation method you want to use, e.g. &#39;Heat exchanger - CHT simulation&#39;. </value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// A meaningful description of the project.
        /// </summary>
        /// <value>A meaningful description of the project.</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProjectCopyRequest {\n");
            sb.Append("  SpaceId: ").Append(SpaceId).Append("\n");
            sb.Append("  ParentFolderId: ").Append(ParentFolderId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProjectCopyRequest);
        }

        /// <summary>
        /// Returns true if ProjectCopyRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ProjectCopyRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProjectCopyRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SpaceId == input.SpaceId ||
                    (this.SpaceId != null &&
                    this.SpaceId.Equals(input.SpaceId))
                ) && 
                (
                    this.ParentFolderId == input.ParentFolderId ||
                    (this.ParentFolderId != null &&
                    this.ParentFolderId.Equals(input.ParentFolderId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SpaceId != null)
                    hashCode = hashCode * 59 + this.SpaceId.GetHashCode();
                if (this.ParentFolderId != null)
                    hashCode = hashCode * 59 + this.ParentFolderId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                return hashCode;
            }
        }

    }

}
