/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// RelativeERPFieldSelection
    /// </summary>
    [DataContract]
    public partial class RelativeERPFieldSelection : OneOfERPCalculationResultControlItemFieldSelection, IEquatable<RelativeERPFieldSelection>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RelativeERPFieldSelection" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RelativeERPFieldSelection() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RelativeERPFieldSelection" /> class.
        /// </summary>
        /// <param name="type">Schema name: RelativeERPFieldSelection (required) (default to &quot;RELATIVE_ERP&quot;).</param>
        /// <param name="referenceERPValue">referenceERPValue.</param>
        public RelativeERPFieldSelection(string type = "RELATIVE_ERP", DimensionalPower referenceERPValue = default(DimensionalPower))
        {
            // to ensure "type" is required (not null)
            this.Type = type ?? throw new ArgumentNullException("type is a required property for RelativeERPFieldSelection and cannot be null");
            this.ReferenceERPValue = referenceERPValue;
        }
        
        /// <summary>
        /// Schema name: RelativeERPFieldSelection
        /// </summary>
        /// <value>Schema name: RelativeERPFieldSelection</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceERPValue
        /// </summary>
        [DataMember(Name="referenceERPValue", EmitDefaultValue=false)]
        public DimensionalPower ReferenceERPValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RelativeERPFieldSelection {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  ReferenceERPValue: ").Append(ReferenceERPValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RelativeERPFieldSelection);
        }

        /// <summary>
        /// Returns true if RelativeERPFieldSelection instances are equal
        /// </summary>
        /// <param name="input">Instance of RelativeERPFieldSelection to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RelativeERPFieldSelection input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.ReferenceERPValue == input.ReferenceERPValue ||
                    (this.ReferenceERPValue != null &&
                    this.ReferenceERPValue.Equals(input.ReferenceERPValue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.ReferenceERPValue != null)
                    hashCode = hashCode * 59 + this.ReferenceERPValue.GetHashCode();
                return hashCode;
            }
        }

    }

}
