/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// SubspaceCoefficient
    /// </summary>
    [DataContract]
    public partial class SubspaceCoefficient : OneOfBatheWilsonSubspaceSettings, OneOfIRAMSorensenSubspaceSettings, OneOfLanczosSubspaceSettings, IEquatable<SubspaceCoefficient>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubspaceCoefficient" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SubspaceCoefficient() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubspaceCoefficient" /> class.
        /// </summary>
        /// <param name="type">Schema name: SubspaceCoefficient (required) (default to &quot;SUBSPACE_COEFFICIENT&quot;).</param>
        /// <param name="subspaceCoefficient">&lt;p&gt;Choose a coefficient (&lt;i&gt;c&lt;sub&gt;ss&lt;/sub&gt;&lt;/i&gt;) with which the subspace dimension (&lt;i&gt;d&lt;sub&gt;ss&lt;/sub&gt;&lt;/i&gt;) is calculated, depending on the number of computed frequencies (&lt;i&gt;n&lt;sub&gt;f&lt;/sub&gt;&lt;/i&gt;):&lt;br&gt; &lt;li&gt;&lt;b&gt;IRAM Sorensen&lt;/b&gt;: &lt;i&gt;d&lt;sub&gt;ss&lt;/sub&gt; &#x3D; &lt;i&gt;max(2 + n&lt;sub&gt;f&lt;/sub&gt; , c&lt;sub&gt;ss&lt;/sub&gt; * n&lt;sub&gt;f&lt;/sub&gt;&lt;/i&gt;).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Lanczos &amp; Bathe - Wilson&lt;/b&gt;: &lt;i&gt;d&lt;sub&gt;ss&lt;/sub&gt; &#x3D; &lt;i&gt;max(7 + n&lt;sub&gt;f&lt;/sub&gt; , c&lt;sub&gt;ss&lt;/sub&gt; * n&lt;sub&gt;f&lt;/sub&gt;&lt;/i&gt;).&lt;/li&gt;&lt;/p&gt;.</param>
        public SubspaceCoefficient(string type = "SUBSPACE_COEFFICIENT", int? subspaceCoefficient = default(int?))
        {
            // to ensure "type" is required (not null)
            this.Type = type ?? throw new ArgumentNullException("type is a required property for SubspaceCoefficient and cannot be null");
            this._SubspaceCoefficient = subspaceCoefficient;
        }
        
        /// <summary>
        /// Schema name: SubspaceCoefficient
        /// </summary>
        /// <value>Schema name: SubspaceCoefficient</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// &lt;p&gt;Choose a coefficient (&lt;i&gt;c&lt;sub&gt;ss&lt;/sub&gt;&lt;/i&gt;) with which the subspace dimension (&lt;i&gt;d&lt;sub&gt;ss&lt;/sub&gt;&lt;/i&gt;) is calculated, depending on the number of computed frequencies (&lt;i&gt;n&lt;sub&gt;f&lt;/sub&gt;&lt;/i&gt;):&lt;br&gt; &lt;li&gt;&lt;b&gt;IRAM Sorensen&lt;/b&gt;: &lt;i&gt;d&lt;sub&gt;ss&lt;/sub&gt; &#x3D; &lt;i&gt;max(2 + n&lt;sub&gt;f&lt;/sub&gt; , c&lt;sub&gt;ss&lt;/sub&gt; * n&lt;sub&gt;f&lt;/sub&gt;&lt;/i&gt;).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Lanczos &amp; Bathe - Wilson&lt;/b&gt;: &lt;i&gt;d&lt;sub&gt;ss&lt;/sub&gt; &#x3D; &lt;i&gt;max(7 + n&lt;sub&gt;f&lt;/sub&gt; , c&lt;sub&gt;ss&lt;/sub&gt; * n&lt;sub&gt;f&lt;/sub&gt;&lt;/i&gt;).&lt;/li&gt;&lt;/p&gt;
        /// </summary>
        /// <value>&lt;p&gt;Choose a coefficient (&lt;i&gt;c&lt;sub&gt;ss&lt;/sub&gt;&lt;/i&gt;) with which the subspace dimension (&lt;i&gt;d&lt;sub&gt;ss&lt;/sub&gt;&lt;/i&gt;) is calculated, depending on the number of computed frequencies (&lt;i&gt;n&lt;sub&gt;f&lt;/sub&gt;&lt;/i&gt;):&lt;br&gt; &lt;li&gt;&lt;b&gt;IRAM Sorensen&lt;/b&gt;: &lt;i&gt;d&lt;sub&gt;ss&lt;/sub&gt; &#x3D; &lt;i&gt;max(2 + n&lt;sub&gt;f&lt;/sub&gt; , c&lt;sub&gt;ss&lt;/sub&gt; * n&lt;sub&gt;f&lt;/sub&gt;&lt;/i&gt;).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Lanczos &amp; Bathe - Wilson&lt;/b&gt;: &lt;i&gt;d&lt;sub&gt;ss&lt;/sub&gt; &#x3D; &lt;i&gt;max(7 + n&lt;sub&gt;f&lt;/sub&gt; , c&lt;sub&gt;ss&lt;/sub&gt; * n&lt;sub&gt;f&lt;/sub&gt;&lt;/i&gt;).&lt;/li&gt;&lt;/p&gt;</value>
        [DataMember(Name="subspaceCoefficient", EmitDefaultValue=false)]
        public int? _SubspaceCoefficient { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubspaceCoefficient {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  _SubspaceCoefficient: ").Append(_SubspaceCoefficient).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SubspaceCoefficient);
        }

        /// <summary>
        /// Returns true if SubspaceCoefficient instances are equal
        /// </summary>
        /// <param name="input">Instance of SubspaceCoefficient to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubspaceCoefficient input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this._SubspaceCoefficient == input._SubspaceCoefficient ||
                    (this._SubspaceCoefficient != null &&
                    this._SubspaceCoefficient.Equals(input._SubspaceCoefficient))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this._SubspaceCoefficient != null)
                    hashCode = hashCode * 59 + this._SubspaceCoefficient.GetHashCode();
                return hashCode;
            }
        }

    }

}
