/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// YeohHyperElasticModel
    /// </summary>
    [DataContract]
    public partial class YeohHyperElasticModel : OneOfHyperElasticMaterialBehaviorHyperElasticModel, IEquatable<YeohHyperElasticModel>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="YeohHyperElasticModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected YeohHyperElasticModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="YeohHyperElasticModel" /> class.
        /// </summary>
        /// <param name="type">Schema name: YeohHyperElasticModel (required) (default to &quot;YEOH&quot;).</param>
        /// <param name="c10">c10.</param>
        /// <param name="c20">c20.</param>
        /// <param name="c30">c30.</param>
        /// <param name="d1">d1.</param>
        public YeohHyperElasticModel(string type = "YEOH", DimensionalPressure c10 = default(DimensionalPressure), DimensionalPressure c20 = default(DimensionalPressure), DimensionalPressure c30 = default(DimensionalPressure), DimensionalInvPressure d1 = default(DimensionalInvPressure))
        {
            // to ensure "type" is required (not null)
            this.Type = type ?? throw new ArgumentNullException("type is a required property for YeohHyperElasticModel and cannot be null");
            this.C10 = c10;
            this.C20 = c20;
            this.C30 = c30;
            this.D1 = d1;
        }
        
        /// <summary>
        /// Schema name: YeohHyperElasticModel
        /// </summary>
        /// <value>Schema name: YeohHyperElasticModel</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets C10
        /// </summary>
        [DataMember(Name="c10", EmitDefaultValue=false)]
        public DimensionalPressure C10 { get; set; }

        /// <summary>
        /// Gets or Sets C20
        /// </summary>
        [DataMember(Name="c20", EmitDefaultValue=false)]
        public DimensionalPressure C20 { get; set; }

        /// <summary>
        /// Gets or Sets C30
        /// </summary>
        [DataMember(Name="c30", EmitDefaultValue=false)]
        public DimensionalPressure C30 { get; set; }

        /// <summary>
        /// Gets or Sets D1
        /// </summary>
        [DataMember(Name="d1", EmitDefaultValue=false)]
        public DimensionalInvPressure D1 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class YeohHyperElasticModel {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  C10: ").Append(C10).Append("\n");
            sb.Append("  C20: ").Append(C20).Append("\n");
            sb.Append("  C30: ").Append(C30).Append("\n");
            sb.Append("  D1: ").Append(D1).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as YeohHyperElasticModel);
        }

        /// <summary>
        /// Returns true if YeohHyperElasticModel instances are equal
        /// </summary>
        /// <param name="input">Instance of YeohHyperElasticModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(YeohHyperElasticModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.C10 == input.C10 ||
                    (this.C10 != null &&
                    this.C10.Equals(input.C10))
                ) && 
                (
                    this.C20 == input.C20 ||
                    (this.C20 != null &&
                    this.C20.Equals(input.C20))
                ) && 
                (
                    this.C30 == input.C30 ||
                    (this.C30 != null &&
                    this.C30.Equals(input.C30))
                ) && 
                (
                    this.D1 == input.D1 ||
                    (this.D1 != null &&
                    this.D1.Equals(input.D1))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.C10 != null)
                    hashCode = hashCode * 59 + this.C10.GetHashCode();
                if (this.C20 != null)
                    hashCode = hashCode * 59 + this.C20.GetHashCode();
                if (this.C30 != null)
                    hashCode = hashCode * 59 + this.C30.GetHashCode();
                if (this.D1 != null)
                    hashCode = hashCode * 59 + this.D1.GetHashCode();
                return hashCode;
            }
        }

    }

}
