/* 
 * SimScale API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = SimScale.Sdk.Client.OpenAPIDateConverter;

namespace SimScale.Sdk.Model
{
    /// <summary>
    /// YeohPrimaryNetwork
    /// </summary>
    [DataContract]
    public partial class YeohPrimaryNetwork : IEquatable<YeohPrimaryNetwork>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="YeohPrimaryNetwork" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected YeohPrimaryNetwork() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="YeohPrimaryNetwork" /> class.
        /// </summary>
        /// <param name="type">Schema name: YeohPrimaryNetwork (required) (default to &quot;YEOH_PRIMARY_NETWORK&quot;).</param>
        /// <param name="c10">c10.</param>
        /// <param name="c20">c20.</param>
        /// <param name="c30">c30.</param>
        /// <param name="bulkModulus">bulkModulus.</param>
        public YeohPrimaryNetwork(string type = "YEOH_PRIMARY_NETWORK", DimensionalPressure c10 = default(DimensionalPressure), DimensionalPressure c20 = default(DimensionalPressure), DimensionalPressure c30 = default(DimensionalPressure), DimensionalPressure bulkModulus = default(DimensionalPressure))
        {
            // to ensure "type" is required (not null)
            this.Type = type ?? throw new ArgumentNullException("type is a required property for YeohPrimaryNetwork and cannot be null");
            this.C10 = c10;
            this.C20 = c20;
            this.C30 = c30;
            this.BulkModulus = bulkModulus;
        }
        
        /// <summary>
        /// Schema name: YeohPrimaryNetwork
        /// </summary>
        /// <value>Schema name: YeohPrimaryNetwork</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets C10
        /// </summary>
        [DataMember(Name="c10", EmitDefaultValue=false)]
        public DimensionalPressure C10 { get; set; }

        /// <summary>
        /// Gets or Sets C20
        /// </summary>
        [DataMember(Name="c20", EmitDefaultValue=false)]
        public DimensionalPressure C20 { get; set; }

        /// <summary>
        /// Gets or Sets C30
        /// </summary>
        [DataMember(Name="c30", EmitDefaultValue=false)]
        public DimensionalPressure C30 { get; set; }

        /// <summary>
        /// Gets or Sets BulkModulus
        /// </summary>
        [DataMember(Name="bulkModulus", EmitDefaultValue=false)]
        public DimensionalPressure BulkModulus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class YeohPrimaryNetwork {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  C10: ").Append(C10).Append("\n");
            sb.Append("  C20: ").Append(C20).Append("\n");
            sb.Append("  C30: ").Append(C30).Append("\n");
            sb.Append("  BulkModulus: ").Append(BulkModulus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as YeohPrimaryNetwork);
        }

        /// <summary>
        /// Returns true if YeohPrimaryNetwork instances are equal
        /// </summary>
        /// <param name="input">Instance of YeohPrimaryNetwork to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(YeohPrimaryNetwork input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.C10 == input.C10 ||
                    (this.C10 != null &&
                    this.C10.Equals(input.C10))
                ) && 
                (
                    this.C20 == input.C20 ||
                    (this.C20 != null &&
                    this.C20.Equals(input.C20))
                ) && 
                (
                    this.C30 == input.C30 ||
                    (this.C30 != null &&
                    this.C30.Equals(input.C30))
                ) && 
                (
                    this.BulkModulus == input.BulkModulus ||
                    (this.BulkModulus != null &&
                    this.BulkModulus.Equals(input.BulkModulus))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.C10 != null)
                    hashCode = hashCode * 59 + this.C10.GetHashCode();
                if (this.C20 != null)
                    hashCode = hashCode * 59 + this.C20.GetHashCode();
                if (this.C30 != null)
                    hashCode = hashCode * 59 + this.C30.GetHashCode();
                if (this.BulkModulus != null)
                    hashCode = hashCode * 59 + this.BulkModulus.GetHashCode();
                return hashCode;
            }
        }

    }

}
